version: "2.4"
services:  
  db:
    image: postgres:12.0-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: vice_node_boilerplate
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: topsecret
    healthcheck:
      test: nc -z localhost 5432 || exit -1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 2s
volumes:
  pg-data: